name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: CI=false yarn build
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PV247_GAME_OF_LIFE }}'
          channelId: live
          projectId: pv247-game-of-life
