name: Lighthouse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: CI=false yarn build

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun
